name = "esp32s3_application"
description = "ESP32S3 Application Template"
version = "0.2.0-dev"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["embedded", "esp32s3"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = true

[[depends-on]]
a0b_base = "*"
a0b_tools = "*"
gnat_xtensa_esp32_elf = "^15"
xtensa_dynconfig = "*"

[[pins]]
a0b_tools = { path='crates/a0b-tools' }
xtensa_dynconfig = { path='crates/xtensa-dynconfig' }

[[actions]]
type = 'post-build'
# esp-idf expects a library as an externally built project.
# Since we build a partially linked elf file it fails to
# generate the linker scripts as their tool looks for the
# "In archive" that objdump prints only for libraries. To
# solve that we just put the elf file into a static library.
command = ['ar', 'rcs', '.objs/main.a', '.objs/main']
